In [7]:
#пример 1.2.1 
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[:,1])
print(x.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[ 2  4  6  8 10]
(5, 2)


In [12]:
#пример 1.2.2 
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(0,100)
print(a,"\n", b,"\n", c,"\n", d,"\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 



In [17]:
# пример 1.2.3
import numpy as np
z = np.random.random((10,10))
zmin= z.min()
zmax = z.max()
zmean = z.mean()
print(z)
print(zmin)
print(zmax)
print(zmean)

[[0.22572395 0.37108765 0.52854474 0.83306842 0.43964548 0.88219101
  0.11191888 0.27355096 0.42197718 0.28504547]
 [0.29251692 0.92854129 0.83012087 0.14682721 0.98704468 0.48523301
  0.81451935 0.43494423 0.28182716 0.16971343]
 [0.99490975 0.57019088 0.5664353  0.34555298 0.91090623 0.44866995
  0.20362729 0.11612183 0.10827443 0.2538319 ]
 [0.68898041 0.4923884  0.50652171 0.15093843 0.10291526 0.86482981
  0.28461412 0.9595058  0.1171936  0.57844103]
 [0.74566046 0.83392028 0.22854397 0.63900667 0.04543941 0.64826688
  0.175146   0.2972916  0.0252991  0.27325889]
 [0.3830863  0.08215106 0.70360592 0.01362972 0.11305591 0.46230804
  0.18284667 0.87939954 0.68113371 0.34051726]
 [0.26728417 0.80110695 0.45770171 0.79388714 0.96405143 0.78197681
  0.43175636 0.3619928  0.41203983 0.12814167]
 [0.21794599 0.61836513 0.71317025 0.9546941  0.09521168 0.7329646
  0.99763749 0.41111294 0.62116056 0.02672382]
 [0.04781087 0.28594268 0.52084241 0.57617539 0.68399802 0.87586688
  0.98290513 

In [21]:
#пример 1.2.4
import numpy as np
a = np.arange(25).reshape(5,5)
print(a)
a[[0,1]] = a [[1,0]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [23]:
# пример 1.2.5
import numpy as np
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==0.1*3)

nan
False
False
nan
False


In [24]:
# пример 1.2.6
import numpy as np
arr = np.array([2,5,76,1,135,79,34,11,315,7375,5555])
print(np.sort(arr))

[   1    2    5   11   34   76   79  135  315 5555 7375]


In [51]:
#задание 1.3.1 Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
#единицами
import numpy as np
a = np.zeros((8,8))
a[1::2,0::2] = 1
a[0::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [55]:
#задание 1.3.2 Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
#необходимо использовать функцию arrange.
import numpy as np
a = np.zeros((5,5))
a = a + np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [57]:
#задание 1.3.3 Создать массив 3x3x3 со случайными значениями
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.88141036 0.90290349 0.79974107]
  [0.7842625  0.97871889 0.69912735]
  [0.81090504 0.60321577 0.85933902]]

 [[0.983565   0.78661951 0.15663096]
  [0.53435812 0.57004693 0.6467236 ]
  [0.37626175 0.5790628  0.04058602]]

 [[0.19184971 0.67327266 0.97467754]
  [0.90806274 0.01041682 0.30999869]
  [0.59383321 0.75238618 0.15678043]]]


In [2]:
#задание 1.3.4 Создать матрицу с 0 внутри, и 1 на границах
import numpy as np
a = np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [3]:
#задание 1.3.5 Создайте массив и отсортируйте его по убыванию
import numpy as np
c=int(input())
a = np.random.random((c,c))
print(np.sort(a))


12
[[0.08240339 0.16026372 0.16995435 0.22875191 0.24193164 0.29516355
  0.38170589 0.40651827 0.42280919 0.43350627 0.45203564 0.54333819]
 [0.08250716 0.0899354  0.12095404 0.28413574 0.32490098 0.32682329
  0.63025509 0.64339554 0.79605593 0.79733654 0.89582624 0.99219635]
 [0.1888064  0.25403672 0.37605211 0.4790027  0.6243804  0.65851016
  0.70032215 0.70457747 0.84395484 0.92266277 0.94064157 0.94877758]
 [0.03763364 0.07922805 0.25250543 0.30462714 0.35886747 0.39599612
  0.39741706 0.57718863 0.66529914 0.67159049 0.78011788 0.89525263]
 [0.01249011 0.05463419 0.13318954 0.24416982 0.29312795 0.33731893
  0.4507624  0.5072418  0.57649682 0.62867292 0.71275502 0.71803918]
 [0.01791993 0.01794557 0.08686196 0.16613268 0.19200799 0.3488665
  0.35335167 0.40365209 0.41139705 0.72277902 0.72958691 0.84461597]
 [0.1315782  0.218879   0.24787887 0.46307776 0.58166068 0.6265842
  0.72272104 0.76071546 0.80883166 0.88658351 0.92838857 0.95313796]
 [0.06937922 0.18566717 0.19303427 0.229

In [5]:
#задание 1.3.6 Создайте матрицу, выведите ее форму, размер и размерность
import numpy as np
c=int(input())
a = np.random.random((c,c))
print(a.shape)
print(a.size)
print(a.dtype)

10
(10, 10)
100
float64


In [15]:
#пример 2.2.1 
import pandas as pd 
lst = [1,2,3,4,5,6,7,8,9]
di = {'a':1,'b':2,'c':3,'d':4,'e':5}
nparr = np.array([1,2,3,4,5])
s1 = pd.Series(lst)
s2 = pd.Series(di)
s3 = pd.Series(nparr,['a','b','c','d','e'])
#print(s1)
#print(s2)
print(s3)

a    1
b    2
c    3
d    4
e    5
dtype: int32


In [24]:
#пример 2.2.2 
import pandas as pd 
s1 = pd.Series([1,2,3,4,5],['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[1:])

3    2
4    1
dtype: int64


In [13]:
#пример 2.2.3
import pandas as pd 
dataframe = pd.DataFrame()
dataframe['Name'] = ['a','b']
dataframe['Age'] = [100,21421]
dataframe['Driver'] = [True, False]
dataframe

Name    Age  Driver
0    a    100    True
1    b  21421   False

In [15]:
#пример 2.2.4
import pandas as pd 
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(6)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   
5                             Anderson, Mr Harry    1st  47.00    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0  
5         1        0

In [19]:
#пример 2.2.5
import pandas as pd 
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)
#dataframe.tail(1)
#dataframe.shape
#почему сразу все не выводит?


Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [21]:
#пример 2.2.6
import pandas as pd 
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.iloc[10:15]

Name PClass   Age     Sex  \
10                         Astor, Colonel John Jacob    1st  47.0    male   
11  Astor, Mrs John Jacob (Madeleine Talmadge Force)    1st  19.0  female   
12                      Aubert, Mrs Leontine Pauline    1st   NaN  female   
13                          Barkworth, Mr Algernon H    1st   NaN    male   
14                                Baumann, Mr John D    1st   NaN    male   

    Survived  SexCode  
10         0        0  
11         1        1  
12         1        1  
13         1        0  
14         0        0

In [25]:
#пример 2.2.7
import pandas as pd 
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe[dataframe['PClass'] == '1st'].head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [29]:
#задание 2.3.1 Найдите евклидово расстояние между двумя Series (точками) a и b,
#не используя встроенную формулу.
import pandas as pd
import math
xij = [3,6]
yij = [100,11]

s1 = pd.Series(xij)
s2 = pd.Series(yij)
Dij = math.sqrt((s1[0] - s2[0])**2 + (s1[1] - s2[1])**2)
print(Dij)

97.12878049270464


In [31]:
#задание 2.3.2 Найдите в Интернете ссылку на любой csv файл и сформируйте из него
#фрейм данных : https://github.com/akmand/datasets) 
import pandas as pd
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe

Name PClass    Age     Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00  female   
1                       Allison, Miss Helen Loraine    1st   2.00  female   
2               Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                     Allison, Master Hudson Trevor    1st   0.92    male   
...                                             ...    ...    ...     ...   
1308                             Zakarian, Mr Artun    3rd  27.00    male   
1309                         Zakarian, Mr Maprieder    3rd  26.00    male   
1310                               Zenni, Mr Philip    3rd  22.00    male   
1311                               Lievens, Mr Rene    3rd  24.00    male   
1312                                 Zimmerman, Leo    3rd  29.00    male   

      Survived  SexCode  
0            1        1  
1            0        1  
2            0        0  
3            0        1  
4            1        0  
...        ...      ...  
1308         0        0  
1309         0        0  
1310         0        0  
1311         0        0  
1312         0        0  

[1313 rows x 6 columns]

In [32]:
#задание 2.3.3 Проделайте с получившемся из предыдущего задания фреймом
#данных те же действия, что и в примерах 2.2.5-2.2.7
import pandas as pd


In [36]:
#пример 3.2.1
import numpy as np 
from sklearn import preprocessing
feature = np.array([[-500.5],[-100,1],[0],[100.1],[900.9]], dtype = float)
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

In [39]:
#пример 3.2.2
import numpy as np
from sklearn import preprocessing

x = np.array([[-1000.1],[-200.2],[-500.5],[600.6],[9000.9]])

scaler = preprocessing.StandardScaler()

standardized = scaler.fit_transform(x)

print(standardized)

print(round(standardized.mean()))
print(standardized.std())



[[-0.68869611]
 [-0.47519348]
 [-0.55534705]
 [-0.26145063]
 [ 1.98068727]]
0
1.0


In [45]:
#пример 3.2.3
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91,21],
                      'B':[103.02,107.26,110.35,114.23,114.68],
                      'C':['big','small','big','small','small']})
dfTest[['A','B']] = scaler.fit_transform(dfTest[['A','B']])
dfTest

ValueError: All arrays must be of the same length